-- ============================================================================
-- Money Manager — one-time Supabase setup
-- Generated by concatenating supabase/migrations/*.sql in order. Paste this
-- whole file into Supabase Dashboard > SQL Editor > New query > Run.
--
-- This is a convenience copy for manual setup only. Going forward, schema
-- changes belong in a new file under supabase/migrations/, never a manual
-- dashboard edit (RULES.md §7) — supabase/migrations/ stays the source of truth.
-- ============================================================================


-- ============================================================================
-- 0001: extensions and helpers
-- ============================================================================

-- Shared trigger function used by every table to keep updated_at current.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ============================================================================
-- 0002: accounts
-- ============================================================================

-- Accounts register (config/reference data, editable per-user).
-- DATA_MODEL.md §7: account name, type (Cash/Savings/Trading/PF/etc), opening
-- balance, currency, active flag.

create table public.accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  type text not null,
  opening_balance numeric(12,2) not null default 0,
  currency text not null default 'INR',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create trigger set_updated_at
  before update on public.accounts
  for each row execute function public.set_updated_at();

alter table public.accounts enable row level security;

create policy "accounts_select_own" on public.accounts
  for select using (auth.uid() = user_id);

create policy "accounts_insert_own" on public.accounts
  for insert with check (auth.uid() = user_id);

create policy "accounts_update_own" on public.accounts
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "accounts_delete_own" on public.accounts
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0003: categories
-- ============================================================================

-- Income/Expense/Transfer categories (config/reference data).
-- DATA_MODEL.md §7: categories table with a type enum, seeded with defaults,
-- editable per-user. Sub-categories are free text on transactions in v1 (see
-- DATA_MODEL.md §1: sub_category "free text or FK to sub-category list").

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  type text not null check (type in ('Income', 'Expense', 'Transfer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name, type)
);

create trigger set_updated_at
  before update on public.categories
  for each row execute function public.set_updated_at();

alter table public.categories enable row level security;

create policy "categories_select_own" on public.categories
  for select using (auth.uid() = user_id);

create policy "categories_insert_own" on public.categories
  for insert with check (auth.uid() = user_id);

create policy "categories_update_own" on public.categories
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "categories_delete_own" on public.categories
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0004: budget_limits
-- ============================================================================

-- Monthly ₹ limit per expense category — drives dashboard over-budget warnings
-- (DATA_MODEL.md §7, §8).

create table public.budget_limits (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category_id uuid not null references public.categories(id) on delete cascade,
  monthly_limit numeric(12,2) not null check (monthly_limit >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, category_id)
);

create trigger set_updated_at
  before update on public.budget_limits
  for each row execute function public.set_updated_at();

alter table public.budget_limits enable row level security;

create policy "budget_limits_select_own" on public.budget_limits
  for select using (auth.uid() = user_id);

create policy "budget_limits_insert_own" on public.budget_limits
  for insert with check (auth.uid() = user_id);

create policy "budget_limits_update_own" on public.budget_limits
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "budget_limits_delete_own" on public.budget_limits
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0005: transactions
-- ============================================================================

-- Core income/expense/transfer ledger (DATA_MODEL.md §1).
-- month is derived (date_trunc('month', date)) — computed in queries, not stored.

create table public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  type text not null check (type in ('Income', 'Expense', 'Transfer')),
  category_id uuid references public.categories(id) on delete set null,
  sub_category text,
  amount numeric(12,2) not null check (amount > 0),
  from_account_id uuid not null references public.accounts(id) on delete restrict,
  to_account_id uuid references public.accounts(id) on delete restrict,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index transactions_user_date_idx on public.transactions (user_id, date desc);
create index transactions_user_category_idx on public.transactions (user_id, category_id);

create trigger set_updated_at
  before update on public.transactions
  for each row execute function public.set_updated_at();

alter table public.transactions enable row level security;

create policy "transactions_select_own" on public.transactions
  for select using (auth.uid() = user_id);

create policy "transactions_insert_own" on public.transactions
  for insert with check (auth.uid() = user_id);

create policy "transactions_update_own" on public.transactions
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "transactions_delete_own" on public.transactions
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0006: investment_log
-- ============================================================================

-- Every buy/sell/SIP/dividend/bonus/split event (DATA_MODEL.md §2).
--
-- total_cashflow is a per-row GENERATED column, not a cross-row aggregate —
-- this encodes the business rule once at the DB level instead of duplicating
-- it in every dependent query, matching the exact rule in DATA_MODEL.md §2:
--   BONUS/SPLIT  -> 0
--   SELL         -> quantity * price - fees
--   DIVIDEND     -> price (price field holds dividend amount received)
--   BUY/SIP      -> -(quantity * price + fees)

create table public.investment_log (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  symbol text not null,
  exchange text not null,
  action text not null check (action in ('BUY', 'SELL', 'SIP', 'DIVIDEND', 'BONUS', 'SPLIT')),
  quantity numeric not null check (quantity >= 0),
  price numeric(12,4) not null check (price >= 0),
  fees numeric(12,2) not null default 0 check (fees >= 0),
  bonus_split_extra_units numeric,
  linked_account_id uuid not null references public.accounts(id) on delete restrict,
  asset_type text not null check (asset_type in ('Stock', 'ETF', 'Mutual Fund', 'Crypto', 'Bond', 'Other')),
  notes text,
  total_cashflow numeric(14,2) generated always as (
    case
      when action in ('BONUS', 'SPLIT') then 0
      when action = 'SELL' then quantity * price - fees
      when action = 'DIVIDEND' then price
      else -(quantity * price + fees)
    end
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index investment_log_user_symbol_idx on public.investment_log (user_id, symbol);
create index investment_log_user_date_idx on public.investment_log (user_id, date desc);

create trigger set_updated_at
  before update on public.investment_log
  for each row execute function public.set_updated_at();

alter table public.investment_log enable row level security;

create policy "investment_log_select_own" on public.investment_log
  for select using (auth.uid() = user_id);

create policy "investment_log_insert_own" on public.investment_log
  for insert with check (auth.uid() = user_id);

create policy "investment_log_update_own" on public.investment_log
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "investment_log_delete_own" on public.investment_log
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0007: holdings
-- ============================================================================

-- Per-symbol manual live price override (DATA_MODEL.md §3: "live_price = manual
-- field, user-editable — no reliable free live-price API for most Indian mutual
-- funds/bonds/gold"). This is plain user input, NOT the derived portfolio view —
-- the portfolio view (units_held, avg_buy_price, P&L, allocation %) is built in
-- Phase 3 on top of investment_log + this table.

create table public.holdings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  display_name text,
  live_price numeric(12,4) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, symbol)
);

create trigger set_updated_at
  before update on public.holdings
  for each row execute function public.set_updated_at();

alter table public.holdings enable row level security;

create policy "holdings_select_own" on public.holdings
  for select using (auth.uid() = user_id);

create policy "holdings_insert_own" on public.holdings
  for insert with check (auth.uid() = user_id);

create policy "holdings_update_own" on public.holdings
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "holdings_delete_own" on public.holdings
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0008: goals
-- ============================================================================

-- Savings goals (DATA_MODEL.md §4). progress_pct, sip_needed_per_month, and
-- status are derived per-goal formulas — computed in packages/shared/logic,
-- not stored (RULES.md §14).

create table public.goals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  goal_name text not null,
  category text not null,
  target_amount numeric(12,2) not null check (target_amount > 0),
  saved_amount numeric(12,2) not null default 0 check (saved_amount >= 0),
  target_date date not null,
  priority text not null check (priority in ('High', 'Medium', 'Low')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index goals_user_target_date_idx on public.goals (user_id, target_date);

create trigger set_updated_at
  before update on public.goals
  for each row execute function public.set_updated_at();

alter table public.goals enable row level security;

create policy "goals_select_own" on public.goals
  for select using (auth.uid() = user_id);

create policy "goals_insert_own" on public.goals
  for insert with check (auth.uid() = user_id);

create policy "goals_update_own" on public.goals
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "goals_delete_own" on public.goals
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0009: cashbook
-- ============================================================================

-- Peer lending/borrowing ledger (DATA_MODEL.md §5). match_key, per-entry status,
-- and the Net Due Summary aggregation are derived — computed in packages/shared/logic
-- and a Phase 3 view respectively, not stored here.

create table public.cashbook (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  counterparty text not null,
  flow text not null check (flow in ('Gave', 'Received')),
  amount numeric(12,2) not null check (amount > 0),
  due_date date,
  account_used_id uuid references public.accounts(id) on delete set null,
  loan_id text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index cashbook_user_counterparty_idx on public.cashbook (user_id, counterparty);
create index cashbook_user_loan_id_idx on public.cashbook (user_id, loan_id) where loan_id is not null;

create trigger set_updated_at
  before update on public.cashbook
  for each row execute function public.set_updated_at();

alter table public.cashbook enable row level security;

create policy "cashbook_select_own" on public.cashbook
  for select using (auth.uid() = user_id);

create policy "cashbook_insert_own" on public.cashbook
  for insert with check (auth.uid() = user_id);

create policy "cashbook_update_own" on public.cashbook
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "cashbook_delete_own" on public.cashbook
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0010: assets_fixed_deposits
-- ============================================================================

-- Fixed deposits (DATA_MODEL.md §6). days_left/status are derived per-row,
-- computed in packages/shared/logic.

create table public.assets_fixed_deposits (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  bank text not null,
  principal numeric(12,2) not null check (principal > 0),
  maturity_value numeric(12,2) not null check (maturity_value > 0),
  maturity_date date not null,
  rate_pct numeric(5,2) not null,
  withdrawn boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.assets_fixed_deposits
  for each row execute function public.set_updated_at();

alter table public.assets_fixed_deposits enable row level security;

create policy "assets_fixed_deposits_select_own" on public.assets_fixed_deposits
  for select using (auth.uid() = user_id);

create policy "assets_fixed_deposits_insert_own" on public.assets_fixed_deposits
  for insert with check (auth.uid() = user_id);

create policy "assets_fixed_deposits_update_own" on public.assets_fixed_deposits
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "assets_fixed_deposits_delete_own" on public.assets_fixed_deposits
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0011: assets_gold
-- ============================================================================

-- Gold holdings (DATA_MODEL.md §6). current_value/pnl are derived, computed in
-- packages/shared/logic.

create table public.assets_gold (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  description text not null,
  grams numeric(10,3) not null check (grams > 0),
  rate_per_gram numeric(12,2) not null check (rate_per_gram > 0),
  purchase_value numeric(12,2) not null check (purchase_value >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.assets_gold
  for each row execute function public.set_updated_at();

alter table public.assets_gold enable row level security;

create policy "assets_gold_select_own" on public.assets_gold
  for select using (auth.uid() = user_id);

create policy "assets_gold_insert_own" on public.assets_gold
  for insert with check (auth.uid() = user_id);

create policy "assets_gold_update_own" on public.assets_gold
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "assets_gold_delete_own" on public.assets_gold
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0012: assets_loans_liabilities
-- ============================================================================

-- Liability register (DATA_MODEL.md §6). No derived fields — values entered directly.

create table public.assets_loans_liabilities (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  lender text not null,
  outstanding numeric(12,2) not null check (outstanding >= 0),
  emi numeric(12,2),
  interest_rate_pct numeric(5,2),
  months_left integer,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.assets_loans_liabilities
  for each row execute function public.set_updated_at();

alter table public.assets_loans_liabilities enable row level security;

create policy "assets_loans_liabilities_select_own" on public.assets_loans_liabilities
  for select using (auth.uid() = user_id);

create policy "assets_loans_liabilities_insert_own" on public.assets_loans_liabilities
  for insert with check (auth.uid() = user_id);

create policy "assets_loans_liabilities_update_own" on public.assets_loans_liabilities
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "assets_loans_liabilities_delete_own" on public.assets_loans_liabilities
  for delete using (auth.uid() = user_id);


-- ============================================================================
-- 0013: grants
-- ============================================================================

-- Base table-level privileges for anon/authenticated roles. RLS policies only
-- restrict which rows a role can see once it already has permission to touch
-- the table at all — without this, every request fails with "permission denied
-- for schema public" (42501) before RLS is even evaluated.

grant usage on schema public to anon, authenticated;

grant select, insert, update, delete on all tables in schema public to anon, authenticated;

alter default privileges in schema public
  grant select, insert, update, delete on tables to anon, authenticated;


-- ============================================================================
-- 0014: seed defaults for new user
-- ============================================================================

-- Seeds sensible default categories and one Cash account for every new user,
-- matching DATA_MODEL.md §7: "seeded with defaults, editable per-user". Without
-- this, a brand-new signup has an empty From Account/Category dropdown on every
-- form and can't log a single transaction until they first visit Settings.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.categories (user_id, name, type) values
    (new.id, 'Salary', 'Income'),
    (new.id, 'Investment Returns', 'Income'),
    (new.id, 'Dividend', 'Income'),
    (new.id, 'Other Income', 'Income'),
    (new.id, 'Food & Dining', 'Expense'),
    (new.id, 'Rent', 'Expense'),
    (new.id, 'Utilities', 'Expense'),
    (new.id, 'Transport', 'Expense'),
    (new.id, 'Shopping', 'Expense'),
    (new.id, 'Healthcare', 'Expense'),
    (new.id, 'Entertainment', 'Expense'),
    (new.id, 'Other Expense', 'Expense'),
    (new.id, 'Self Transfer', 'Transfer');

  insert into public.accounts (user_id, name, type, opening_balance, currency, is_active) values
    (new.id, 'Cash', 'Cash', 0, 'INR', true);

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- Extended asset classes (DATA_MODEL.md §6b): EPF, NPS, SSY, SGB, ULIP.
-- ============================================================================

create table public.assets_epf (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  employer_name text not null,
  current_balance numeric(12,2) not null check (current_balance >= 0),
  monthly_contribution numeric(12,2) not null check (monthly_contribution >= 0),
  uan_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.assets_epf
  for each row execute function public.set_updated_at();

alter table public.assets_epf enable row level security;

create policy "assets_epf_select_own" on public.assets_epf
  for select using (auth.uid() = user_id);
create policy "assets_epf_insert_own" on public.assets_epf
  for insert with check (auth.uid() = user_id);
create policy "assets_epf_update_own" on public.assets_epf
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "assets_epf_delete_own" on public.assets_epf
  for delete using (auth.uid() = user_id);

create type public.nps_tier as enum ('Tier I', 'Tier II');

create table public.assets_nps (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  pran_number text not null,
  current_value numeric(12,2) not null check (current_value >= 0),
  tier public.nps_tier not null default 'Tier I',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.assets_nps
  for each row execute function public.set_updated_at();

alter table public.assets_nps enable row level security;

create policy "assets_nps_select_own" on public.assets_nps
  for select using (auth.uid() = user_id);
create policy "assets_nps_insert_own" on public.assets_nps
  for insert with check (auth.uid() = user_id);
create policy "assets_nps_update_own" on public.assets_nps
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "assets_nps_delete_own" on public.assets_nps
  for delete using (auth.uid() = user_id);

create table public.assets_ssy (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  account_holder_name text not null,
  account_number text not null,
  current_balance numeric(12,2) not null check (current_balance >= 0),
  opening_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.assets_ssy
  for each row execute function public.set_updated_at();

alter table public.assets_ssy enable row level security;

create policy "assets_ssy_select_own" on public.assets_ssy
  for select using (auth.uid() = user_id);
create policy "assets_ssy_insert_own" on public.assets_ssy
  for insert with check (auth.uid() = user_id);
create policy "assets_ssy_update_own" on public.assets_ssy
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "assets_ssy_delete_own" on public.assets_ssy
  for delete using (auth.uid() = user_id);

create table public.assets_sgb (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  units_held numeric(10,3) not null check (units_held > 0),
  issue_price numeric(12,4) not null check (issue_price > 0),
  issue_date date not null,
  rate_per_gram numeric(12,4) not null check (rate_per_gram > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.assets_sgb
  for each row execute function public.set_updated_at();

alter table public.assets_sgb enable row level security;

create policy "assets_sgb_select_own" on public.assets_sgb
  for select using (auth.uid() = user_id);
create policy "assets_sgb_insert_own" on public.assets_sgb
  for insert with check (auth.uid() = user_id);
create policy "assets_sgb_update_own" on public.assets_sgb
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "assets_sgb_delete_own" on public.assets_sgb
  for delete using (auth.uid() = user_id);

create type public.ulip_premium_frequency as enum ('Monthly', 'Quarterly', 'Half-Yearly', 'Yearly');

create table public.assets_ulip (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  insurer text not null,
  policy_number text not null,
  sum_assured numeric(12,2) not null check (sum_assured >= 0),
  current_fund_value numeric(12,2) not null check (current_fund_value >= 0),
  premium_amount numeric(12,2) not null check (premium_amount >= 0),
  premium_frequency public.ulip_premium_frequency not null default 'Yearly',
  maturity_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.assets_ulip
  for each row execute function public.set_updated_at();

alter table public.assets_ulip enable row level security;

create policy "assets_ulip_select_own" on public.assets_ulip
  for select using (auth.uid() = user_id);
create policy "assets_ulip_insert_own" on public.assets_ulip
  for insert with check (auth.uid() = user_id);
create policy "assets_ulip_update_own" on public.assets_ulip
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "assets_ulip_delete_own" on public.assets_ulip
  for delete using (auth.uid() = user_id);

-- ============================================================================
-- user_profiles + insurance_policies (DATA_MODEL.md §9, §10).
-- ============================================================================

create table public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  date_of_birth date,
  monthly_income numeric(12,2),
  monthly_expense numeric(12,2),
  number_of_dependents integer not null default 0 check (number_of_dependents >= 0),
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.user_profiles
  for each row execute function public.set_updated_at();

alter table public.user_profiles enable row level security;

create policy "user_profiles_select_own" on public.user_profiles
  for select using (auth.uid() = user_id);
create policy "user_profiles_insert_own" on public.user_profiles
  for insert with check (auth.uid() = user_id);
create policy "user_profiles_update_own" on public.user_profiles
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "user_profiles_delete_own" on public.user_profiles
  for delete using (auth.uid() = user_id);

create type public.insurance_policy_type as enum ('Term', 'Health', 'Motor', 'Other');

create table public.insurance_policies (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  policy_type public.insurance_policy_type not null,
  insurer text not null,
  policy_number text not null,
  coverage_amount numeric(12,2) not null check (coverage_amount >= 0),
  premium_amount numeric(12,2) not null check (premium_amount >= 0),
  premium_due_date date not null,
  nominee text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.insurance_policies
  for each row execute function public.set_updated_at();

alter table public.insurance_policies enable row level security;

create policy "insurance_policies_select_own" on public.insurance_policies
  for select using (auth.uid() = user_id);
create policy "insurance_policies_insert_own" on public.insurance_policies
  for insert with check (auth.uid() = user_id);
create policy "insurance_policies_update_own" on public.insurance_policies
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "insurance_policies_delete_own" on public.insurance_policies
  for delete using (auth.uid() = user_id);

-- ============================================================================
-- Done. 19 tables created, all with RLS enabled and 4 policies each, plus the
-- base grants anon/authenticated need to reach them, plus default categories
-- and a Cash account seeded automatically for every new signup.
-- Next: Authentication > Providers, enable Email + Google in your Supabase
-- dashboard so the app's sign-up/sign-in flow works.
-- ============================================================================
